name: Sync branches
on:
  push:
    branches: [main]

jobs:
  sync-branches:
    name: Sync branches
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Merge main -> dev
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "<>"
          git fetch --unshallow
          git checkout dev
          git pull
          git merge main -m 'chore: merge main into dev'
          git push
