name: Sync branches
on:
  push:
    branches: [main]

jobs:
  sync-branches:
    name: Sync branches
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Merge main -> dev
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "<>"
          git checkout origin/dev
          git merge -m 'chore: merge main into dev' main
          git push origin dev
