name: Sync branches
on:
  push:
    branches: [main]

jobs:
  sync-branches:
    name: Sync branches
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Merge main -> dev
        uses: devmasx/merge-branch@v1.4.0
        with:
          type: now
          from_branch: main
          target_branch: dev
          github_token: ${{ github.token }}
